/// Flutter icons IconTick
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconTick
///      fonts:
///       - asset: fonts/IconTick.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class IconTick {
  IconTick._();

  static const _kFontFam = 'IconTick';
  static const String? _kFontPkg = null;

  static const IconData ok_circled2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
